"""Parse-only compatibility for out-of-layer constructors (auto-generated).

Telegram's servers serialize hot types from their internal layer regardless of
the layer the client declares (observed 2026-07-13: message#3ae56482 leaked to
layer-211 clients; previously July 2025: message#9815cec8). The overlay
section of api.tl defines those constructors under aliased predicates; this
module rewrites each alias class's from_reader to return the canonical
LAYER-228 class of the same predicate, so downstream code only ever sees
standard types. Fields unknown to the canonical class are dropped;
canonical-required fields missing from the alias default to None. Aliases
with no canonical counterpart are left as-is (parseable, flow through raw).

Generated by tl-layer228-build.py — do not edit by hand.
"""

import inspect

from . import types

_PAIRS = [
    ('KeyboardButtonUrlAuthX10b78d29', 'KeyboardButtonUrlAuth'),  # keyboardButtonUrlAuth#10b78d29
    ('UpdateBotChatInviteRequesterX11dfa986', 'UpdateBotChatInviteRequester'),  # updateBotChatInviteRequester#11dfa986
    ('KeyboardButtonWebViewX13767230', 'KeyboardButtonWebView'),  # keyboardButtonWebView#13767230
    ('StarGiftAttributePatternX13acff19', 'StarGiftAttributePattern'),  # starGiftAttributePattern#13acff19
    ('payments.StarGiftUpgradePreviewX167bd90b', 'payments.StarGiftUpgradePreview'),  # payments.starGiftUpgradePreview#167bd90b
    ('UpdateChannelPinnedTopicX192efbe3', None),  # updateChannelPinnedTopic#192efbe3
    ('ChannelX1c32b11c', 'Channel'),  # channel#1c32b11c
    ('SavedStarGiftX1ea646df', 'SavedStarGift'),  # savedStarGift#1ea646df
    ('UserX20b1422', 'User'),  # user#20b1422
    ('UpdateMessagePollVoteX24f40e77', 'UpdateMessagePollVote'),  # updateMessagePollVote#24f40e77
    ('KeyboardButtonUrlX258aff05', 'KeyboardButtonUrl'),  # keyboardButtonUrl#258aff05
    ('PageListItemBlocksX25e073fc', 'PageListItemBlocks'),  # pageListItemBlocks#25e073fc
    ('payments.CheckedGiftCodeX284a1096', 'payments.CheckedGiftCode'),  # payments.checkedGiftCode#284a1096
    ('KeyboardButtonUserProfileX308660c1', 'KeyboardButtonUserProfile'),  # keyboardButtonUserProfile#308660c1
    ('UserX31774388', 'User'),  # user#31774388
    ('MessageActionStarGiftUniqueX34f762f3', 'MessageActionStarGiftUnique'),  # messageActionStarGiftUnique#34f762f3
    ('KeyboardButtonCallbackX35bbdb6b', 'KeyboardButtonCallback'),  # keyboardButtonCallback#35bbdb6b
    ('StarGiftAttributeModelX39d99013', 'StarGiftAttributeModel'),  # starGiftAttributeModel#39d99013
    ('StarGiftUniqueX3a274d50', 'StarGiftUnique'),  # starGiftUnique#3a274d50
    ('MessageX3ae56482', 'Message'),  # message#3ae56482
    ('PollAnswerVotersX3b6ddad2', 'PollAnswerVoters'),  # pollAnswerVoters#3b6ddad2
    ('MessageMediaDiceX3f7ee58b', 'MessageMediaDice'),  # messageMediaDice#3f7ee58b
    ('MessageActionStarGiftX4717e8a4', 'MessageActionStarGift'),  # messageActionStarGift#4717e8a4
    ('MessageMediaPollX4bd6e798', 'MessageMediaPoll'),  # messageMediaPoll#4bd6e798
    ('TodoCompletionX4cc120b7', 'TodoCompletion'),  # todoCompletion#4cc120b7
    ('ChannelParticipantSelfX4f607bef', 'ChannelParticipantSelf'),  # channelParticipantSelf#4f607bef
    ('KeyboardButtonGameX50f41ccf', 'KeyboardButtonGame'),  # keyboardButtonGame#50f41ccf
    ('KeyboardButtonRequestPeerX53d7bfd8', 'KeyboardButtonRequestPeer'),  # keyboardButtonRequestPeer#53d7bfd8
    ('GroupCallX553b0ba1', 'GroupCall'),  # groupCall#553b0ba1
    ('MessageActionGiftCodeX56d03994', 'MessageActionGiftCode'),  # messageActionGiftCode#56d03994
    ('ReactionsNotifySettingsX56e34970', 'ReactionsNotifySettings'),  # reactionsNotifySettings#56e34970
    ('PollX58747131', 'Poll'),  # poll#58747131
    ('PageListOrderedItemTextX5e068047', 'PageListOrderedItemText'),  # pageListOrderedItemText#5e068047
    ('MessageReplyHeaderX6917560b', 'MessageReplyHeader'),  # messageReplyHeader#6917560b
    ('MessageMediaPhotoX695150d7', 'MessageMediaPhoto'),  # messageMediaPhoto#695150d7
    ('MessageActionGiftPremiumX6c6274fa', 'MessageActionGiftPremium'),  # messageActionGiftPremium#6c6274fa
    ('ChannelParticipantBannedX6df8014e', 'ChannelParticipantBanned'),  # channelParticipantBanned#6df8014e
    ('ForumTopicX71701da9', 'ForumTopic'),  # forumTopic#71701da9
    ('KeyboardButtonCopyX75d2698e', 'KeyboardButtonCopy'),  # keyboardButtonCopy#75d2698e
    ('messages.MessagesSliceX762b263d', 'messages.MessagesSlice'),  # messages.messagesSlice#762b263d
    ('PollResultsX7adf2420', 'PollResults'),  # pollResults#7adf2420
    ('UserFullX7e63ce1f', 'UserFull'),  # userFull#7e63ce1f
    ('messages.MessagesX8c718e87', 'messages.Messages'),  # messages.messages#8c718e87
    ('UrlAuthResultAcceptedX8f8c0e4e', 'UrlAuthResultAccepted'),  # urlAuthResultAccepted#8f8c0e4e
    ('UrlAuthResultRequestX92d33a0e', 'UrlAuthResultRequest'),  # urlAuthResultRequest#92d33a0e
    ('KeyboardButtonSwitchInlineX93b9fbb5', 'KeyboardButtonSwitchInline'),  # keyboardButtonSwitchInline#93b9fbb5
    ('DraftMessageX96eaa5eb', 'DraftMessage'),  # draftMessage#96eaa5eb
    ('UpdateGroupCallX97d64341', 'UpdateGroupCall'),  # updateGroupCall#97d64341
    ('MessageX9815cec8', 'Message'),  # message#9815cec8
    ('PageListOrderedItemBlocksX98dd8936', 'PageListOrderedItemBlocks'),  # pageListOrderedItemBlocks#98dd8936
    ('PageBlockOrderedListX9a8ae1e1', 'PageBlockOrderedList'),  # pageBlockOrderedList#9a8ae1e1
    ('UpdateReadHistoryInboxX9c974fdf', 'UpdateReadHistoryInbox'),  # updateReadHistoryInbox#9c974fdf
    ('UserFullXa02bc13e', 'UserFull'),  # userFull#a02bc13e
    ('ChatParticipantAdminXa0933f5b', 'ChatParticipantAdmin'),  # chatParticipantAdmin#a0933f5b
    ('KeyboardButtonSimpleWebViewXa0c0505c', 'KeyboardButtonSimpleWebView'),  # keyboardButtonSimpleWebView#a0c0505c
    ('KeyboardButtonXa2fa4880', 'KeyboardButton'),  # keyboardButton#a2fa4880
    ('MessageActionSetChatThemeXaa786345', 'MessageActionSetChatTheme'),  # messageActionSetChatTheme#aa786345
    ('UpdateMessagePollXaca1657b', 'UpdateMessagePoll'),  # updateMessagePoll#aca1657b
    ('KeyboardButtonBuyXafd93fbb', 'KeyboardButtonBuy'),  # keyboardButtonBuy#afd93fbb
    ('KeyboardButtonRequestPhoneXb16a6c29', 'KeyboardButtonRequestPhone'),  # keyboardButtonRequestPhone#b16a6c29
    ('messages.WebPagePreviewXb53e8b21', 'messages.WebPagePreview'),  # messages.webPagePreview#b53e8b21
    ('PageListItemTextXb92fb6cd', 'PageListItemText'),  # pageListItemText#b92fb6cd
    ('KeyboardButtonRequestPollXbbc7515d', 'KeyboardButtonRequestPoll'),  # keyboardButtonRequestPoll#bbc7515d
    ('StarGiftXbcff5b', 'StarGift'),  # starGift#bcff5b
    ('UpdateUserTypingXc01e857f', 'UpdateUserTyping'),  # updateUserTyping#c01e857f
    ('ChatParticipantXc02d4007', 'ChatParticipant'),  # chatParticipant#c02d4007
    ('BotCommandXc27ac8c7', 'BotCommand'),  # botCommand#c27ac8c7
    ('payments.UniqueStarGiftXcaa2f60b', 'payments.UniqueStarGift'),  # payments.uniqueStarGift#caa2f60b
    ('ChannelParticipantXcb397619', 'ChannelParticipant'),  # channelParticipant#cb397619
    ('ConnectedBotXcd64636c', 'ConnectedBot'),  # connectedBot#cd64636c
    ('ForumTopicXcdff0eca', 'ForumTopic'),  # forumTopic#cdff0eca
    ('DialogXd58a08c6', 'Dialog'),  # dialog#d58a08c6
    ('auth.SentCodePaymentRequiredXd7cef980', 'auth.SentCodePaymentRequired'),  # auth.sentCodePaymentRequired#d7cef980
    ('StarGiftAttributeBackdropXd93d859c', 'StarGiftAttributeBackdrop'),  # starGiftAttributeBackdrop#d93d859c
    ('ChannelFullXe07429de', 'ChannelFull'),  # channelFull#e07429de
    ('auth.SentCodePaymentRequiredXe0955a3c', 'auth.SentCodePaymentRequired'),  # auth.sentCodePaymentRequired#e0955a3c
    ('ChatParticipantCreatorXe46bcee4', 'ChatParticipantCreator'),  # chatParticipantCreator#e46bcee4
    ('ChannelFullXe4e0b29d', 'ChannelFull'),  # channelFull#e4e0b29d
    ('GroupCallParticipantXeba636fe', 'GroupCallParticipant'),  # groupCallParticipant#eba636fe
    ('StoryItemXedf164f1', 'StoryItem'),  # storyItem#edf164f1
    ('UrlAuthResultRequestXf8f8eb1e', 'UrlAuthResultRequest'),  # urlAuthResultRequest#f8f8eb1e
    ('KeyboardButtonRequestGeoLocationXfc796b3f', 'KeyboardButtonRequestGeoLocation'),  # keyboardButtonRequestGeoLocation#fc796b3f
    ('UpdateChannelPinnedTopicsXfe198602', None),  # updateChannelPinnedTopics#fe198602
    ('ChannelXfe685355', 'Channel'),  # channel#fe685355
    ('PollAnswerXff16e2ca', 'PollAnswer'),  # pollAnswer#ff16e2ca,
]


def _resolve(dotted):
    obj = types
    for part in dotted.split('.'):
        obj = getattr(obj, part)
    return obj


def _wrap(alias_cls, base_name):
    # Base resolution is LAZY (first parse) and re-checked against the live
    # types module: telethon/tl/patched/__init__.py replaces types.Message &
    # co. with custom-mixin classes AFTER this module is imported — resolving
    # eagerly would hand downstream the unpatched generated classes.
    orig = alias_cls.from_reader.__func__
    memo = {}

    def from_reader(cls, reader):
        obj = orig(cls, reader)
        base_cls = _resolve(base_name)
        spec = memo.get(base_cls)
        if spec is None:
            optional, required = [], []
            for pname, p in inspect.signature(base_cls.__init__).parameters.items():
                if pname == 'self':
                    continue
                (optional if p.default is not inspect.Parameter.empty
                 else required).append(pname)
            spec = memo[base_cls] = (required, optional)
        required, optional = spec
        kwargs = {name: getattr(obj, name, None) for name in required}
        for name in optional:
            if hasattr(obj, name):
                kwargs[name] = getattr(obj, name)
        return base_cls(**kwargs)

    alias_cls.from_reader = classmethod(from_reader)


def _install():
    for alias_name, base_name in _PAIRS:
        if base_name is None:
            continue
        try:
            alias_cls = _resolve(alias_name)
            _resolve(base_name)
        except AttributeError:
            continue
        _wrap(alias_cls, base_name)


_install()
